POST http://localhost:5000/celebrities
Content-Type: application/json

{
  "celebrity_name": "Donald Trump",
  "prompt": "Declare war on North Korea."
}

###

POST http://localhost:5000/translation
Content-Type: application/json

{
  "sentence": "Der rote Fuchs springt über den faulen Hund."
}

###
