POST http://localhost:5000/check
Content-Type: text/plain

Hey Baywatch!

As you may know, the Hamburg office is pretty dead. So me and a few others were thinking, it might be nice to have a Retrospective for the last few month's social events to see what people would like to do differently. Or to have a Mural or a Questionnaire on what people might want from future events.

The format is not really clear yet; which is why I'm looking for someone on the beach with experience in facilitating spaces like these or designing cool Mural boards.

###
